### PR TITLE
fix: merging titles

### PR DESCRIPTION
**Pull request by mallachari**
Using the first occurrence of title property instead of the last one.
Needed for handling nested allOf where the title should come from the parent schema.

### CODE REVIEW

**Comment by mallachari** [comment]
@P0lip is there a reason for or is it important that the merged title was coming from the last element?

**Comment by P0lip** [comment]
@mallachari yup, we did change it on purpose https://github.com/stoplightio/json-schema-merge-allof/pull/1
Despite its actual purpose, people use `allOf` for "merging", and in most cases, the last occurrence takes precedence there.

cc @marbemac

**Comment by mallachari** [comment]
The reason why I wanted that change is [this issue](https://github.com/stoplightio/platform-internal/issues/8463), where the merged schemas get the titles from the referenced inner object which is the same for all anyOf items making the indistinguishable.

A simplified version of the schema from the issue which produces 2 anyOf schemas both with the same `Inner` title instead of `Option 1` and `Option2`:
```
{
  "type": "array",
  "items": {
    "oneOf": [
      {
        "allOf": [
          {
            "properties": {
              "a": {
                "type": "string"
              }
            }
          },
          {
            "title": "Option 1",
            "allOf": [
              {
                "$ref": "#/__bundled__/someBundledObj"
              },
              {
                "type": "object",
                "properties": {
                  "b": {
                    "type": "string"
                  }
                }
              }
            ]
          }
        ]
      },
      {
        "allOf": [
          {
            "properties": {
              "a": {
                "type": "string"
              }
            }
          },
          {
            "title": "Option 2",
            "allOf": [
              {
                "$ref": "#/__bundled__/someBundledObj"
              },
              {
                "type": "object",
                "properties": {
                  "c": {
                    "type": "string"
                  }
                }
              }
            ]
          }
        ]
      }
    ]
  },
  "__bundled__": {
    "someBundledObj": {
      "title": "Inner",
      "type": "object",
      "properties": {
        "foo": {
          "type": "number"
        },
        "type": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by P0lip** [comment]
@mallachari ah got it.
I think I might have an alternative solution - let me check it, I'll get back to you.

**Comment by mallachari** [comment]
Closing as this is done in https://github.com/stoplightio/json-schema-merge-allof/pull/7#pullrequestreview-798357191

**Pull request closed without merging**
